# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "usbhid" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-aa84c6e2-6181-4df3-95eb-6082665a483c";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-aa84c6e2-6181-4df3-95eb-6082665a483c".device = "/dev/disk/by-uuid/aa84c6e2-6181-4df3-95eb-6082665a483c";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/89F8-F99B";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/data" =
    { device = "/dev/disk/by-uuid/A072C1C972C1A47E";
      fsType = "ntfs3";
      options = [ "rw" "uid=1000" "gid=100" "nofail" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-cfffc0b1-1359-4158-b88c-53d4ebbc5a54"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
